version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=zG6e27hz27a8
    ports:
      - "1433:1433"
    networks:
      - backend

networks:
  backend:
